# Generated by Django 5.1.2 on 2024-12-31 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('inability', models.CharField(max_length=256)),
                ('inability_days', models.IntegerField()),
                ('observations', models.TextField(max_length=256)),
                ('cie10_code', models.CharField(max_length=50)),
                ('cie10_description', models.TextField(max_length=256)),
            ],
        ),
    ]
