# Generated by Django 5.1.2 on 2025-01-31 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service_end_cie10code',
            },
        ),
        migrations.CreateModel(
            name='ServiceEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('inability', models.CharField(max_length=256)),
                ('inability_days', models.IntegerField()),
                ('observations', models.TextField(max_length=256)),
                ('cie10_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ends', to='service_end.cie10code')),
            ],
        ),
    ]
