# Generated by Django 5.1.2 on 2024-12-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inability', models.CharField(max_length=256)),
                ('inability_days', models.IntegerField()),
                ('observations', models.TextField(max_length=256)),
                ('cie10_code', models.CharField(max_length=50)),
                ('cie10_description', models.TextField(max_length=256)),
            ],
        ),
    ]
