# Generated by Django 5.1.2 on 2025-01-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
