# Generated by Django 5.1.2 on 2024-12-31 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('PS', 'PASAPORTE'), ('CE', 'CEDULA DE EXTRANJERIA')], default='CC', max_length=30)),
                ('identification_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('address_departament', models.CharField(default='META', max_length=256)),
                ('address_city', models.CharField(default='VILLAVICENCIO', max_length=256)),
                ('address_line', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rethus', models.CharField(max_length=255, unique=True)),
                ('doctor_type', models.CharField(choices=[('MG', 'MEDICO GENERAL'), ('MS', 'MEDICO ESPECIALISTA'), ('TP', 'TERAPEUTA'), ('EF', 'ENFERMERA')], max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': [('can_edit_doctoruser', 'Can edit doctor user')],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('PS', 'PASAPORTE'), ('CE', 'CEDULA DE EXTRANJERIA')], default='CC', max_length=30)),
                ('identification_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('address_departament', models.CharField(default='META', max_length=256)),
                ('address_city', models.CharField(default='VILLAVICENCIO', max_length=256)),
                ('address_line', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eps', models.CharField(choices=[('EPS1', 'EPS1'), ('EPS2', 'EPS2'), ('EPS3', 'EPS3')], max_length=100)),
                ('prepaid_medicine', models.CharField(choices=[('PREPAID1', 'PREPAID1'), ('PREPAID2', 'PREPAID2'), ('PREPAID3', 'PREPAID3')], max_length=100)),
            ],
            options={
                'permissions': [('can_edit_patientuser', 'Can edit patient user')],
            },
            bases=('users.user',),
        ),
    ]
