# Generated by Django 5.1.2 on 2025-01-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctoruser_gender_patientuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('O', 'OTRO')], default='MASCULINO', max_length=30),
        ),
    ]
