# Generated by Django 5.1.2 on 2025-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('OTRO', 'OTRO')], default='M', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('OTRO', 'OTRO')], default='MASCULINO', max_length=30),
        ),
    ]
