# Generated by Django 5.1.2 on 2024-12-25 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departament', models.CharField(default='META', max_length=256)),
                ('city', models.CharField(default='VILLAVICENCIO', max_length=256)),
                ('line_address', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
    ]
