# Generated by Django 5.1.2 on 2025-01-31 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departament', models.CharField(default='META', max_length=256)),
                ('city', models.CharField(default='VILLAVICENCIO', max_length=256)),
                ('neighborhood', models.CharField(max_length=256)),
                ('line_address', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_address', to='users.patientuser')),
            ],
        ),
    ]
