# Generated by Django 5.1.2 on 2025-01-06 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_address', '0001_initial'),
        ('service_end', '0001_initial'),
        ('users', '0002_doctoruser_gender_patientuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=256)),
                ('type_payment', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], max_length=30)),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA Y EN CAMINO', 'ACEPTADA Y EN CAMINO'), ('LLEGADA AL DOMICILIO', 'LLEGADA AL DOMICILIO'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='service_address.serviceaddress')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_latitude', models.FloatField(blank=True, null=True)),
                ('doctor_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_responses', to='users.doctoruser')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='service_request.patientservicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctoruser')),
                ('doctor_service_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_detail', to='service_request.doctorserviceresponse')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_address.serviceaddress')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientuser')),
                ('patient_service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_detail', to='service_request.patientservicerequest')),
                ('service_end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_detail', to='service_end.serviceend')),
            ],
        ),
    ]
