# Generated by Django 5.1.2 on 2024-10-29 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=256)),
                ('type_payment', models.CharField(choices=[('EF', 'EFECTIVO'), ('TR', 'TRANSFERENCIA')], max_length=30)),
                ('status', models.CharField(choices=[('PD', 'PENDIENTE'), ('AC', 'ACEPTADA'), ('RZ', 'RECHAZADA'), ('CP', 'COMPLETADA')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
