# Generated by Django 5.1.2 on 2024-10-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_address', '0001_initial'),
        ('service_end', '0001_initial'),
        ('service_request', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='users.doctoruser'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='document_service_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_request', to='service_end.serviceend'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_request', to='service_address.serviceaddress'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_request', to='users.patientuser'),
        ),
    ]
