# Generated by Django 5.1.2 on 2024-12-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0003_alter_servicerequestdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
