# Generated by Django 5.1.2 on 2024-12-31 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0004_alter_servicerequestdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
